export const sets = [
  {
    id: "sv8pt5",
    name: "Prismatic Evolutions",
    series: "Scarlet & Violet",
    printedTotal: 131,
    total: 180,
  },
  {
    id: "sv8",
    name: "Surging Sparks",
    series: "Scarlet & Violet",
    printedTotal: 191,
    total: 252,
  },
  {
    id: "sv7",
    name: "Stellar Crown",
    series: "Scarlet & Violet",
    printedTotal: 142,
    total: 175,
  },
  {
    id: "sv6pt5",
    name: "Shrouded Fable",
    series: "Scarlet & Violet",
    printedTotal: 64,
    total: 99,
  },
  {
    id: "sv6",
    name: "Twilight Masquerade",
    series: "Scarlet & Violet",
    printedTotal: 167,
    total: 226,
  },
  {
    id: "sv5",
    name: "Temporal Forces",
    series: "Scarlet & Violet",
    printedTotal: 162,
    total: 218,
  },
  {
    id: "sv4pt5",
    name: "Paldean Fates",
    series: "Scarlet & Violet",
    printedTotal: 91,
    total: 245,
  },
  {
    id: "sv4",
    name: "Paradox Rift",
    series: "Scarlet & Violet",
    printedTotal: 182,
    total: 266,
  },
  {
    id: "sv3pt5",
    name: "151",
    series: "Scarlet & Violet",
    printedTotal: 165,
    total: 207,
  },
  {
    id: "sv3",
    name: "Obsidian Flames",
    series: "Scarlet & Violet",
    printedTotal: 197,
    total: 230,
  },
  {
    id: "sv2",
    name: "Paldea Evolved",
    series: "Scarlet & Violet",
    printedTotal: 193,
    total: 279,
  },
  {
    id: "sv1",
    name: "Scarlet & Violet",
    series: "Scarlet & Violet",
    printedTotal: 198,
    total: 258,
  },
];
